#  ////////*                                              
#         *///////////                                    
# //////////*   ////////////                              
#           ,/////////////////                            
# /////////////////////////////    ./////                 
#            //////////////////   ////// .///             
#     *///////////////////////// .//////.     ///         
#                 //////////////.  */////,*////  .//      
#                   /////////////.     ,/////  ,///* //   
#                     /////////////       /////      ,/*, 
#                      .//////////////.  ///////          
#                         //////////////////////          
#                             ,/////,*/////////           
#                               //////////////            
#                            ///////////////              
#                           /////////////                 
#                         ,/////////*                     
#                    .////////.                           

# This SnakeMake file contains the rule to run CCS
# Project: longread simulation study
# Description: generate the CCS reads from the raw PacBio reads (generated by PBSIM3 with --pass-num 10)
# Author: Paula Uittenbogaard
# Date: 29-04-2025

#######################
## Setting directories
#######################

rule ccs:
    input: 
        f"{pbsim_dir}/{prefix}_0001.bam"
    output:
        f"{ccs_dir}/{prefix}.fastq.gz"
    params:
        outdir = f"{ccs_dir}"
    shell:
        """
        rm -rf {params.outdir}
        mkdir {params.outdir}
        ccs --all {input} {output}
        """

rule align_ccs_reads_to_ref:
    input:
        fq = f"{ccs_dir}/{prefix}.fastq.gz",
        ref = f"{RUN_DIR}/targets/{{TARGETS}}.fasta"
    output:
        bam = f"{ccs_dir}/{prefix}.bam",
        bai = f"{ccs_dir}/{prefix}.bam.bai"
    params:
        tempdir = f"{ccs_dir}/minimap2"
    log:
        f"{ccs_dir}/{prefix}_alignments.log"
    shell:
        """
        minimap2 --MD -ax map-hifi -t 20 {input.ref} {input.fq} | samtools sort -@ 10 -T {params.tempdir} -O BAM -o {output.bam} - 2> {log}; \
        samtools index {output.bam} 2>> {log}
        """