#  ////////*                                              
#         *///////////                                    
# //////////*   ////////////                              
#           ,/////////////////                            
# /////////////////////////////    ./////                 
#            //////////////////   ////// .///             
#     *///////////////////////// .//////.     ///         
#                 //////////////.  */////,*////  .//      
#                   /////////////.     ,/////  ,///* //   
#                     /////////////       /////      ,/*, 
#                      .//////////////.  ///////          
#                         //////////////////////          
#                             ,/////,*/////////           
#                               //////////////            
#                            ///////////////              
#                           /////////////                 
#                         ,/////////*                     
#                    .////////.                           

# This SnakeMake file contains the rule to run raven
# Project: longread simulation study
# Description: perform de novo assembly on the simulated reads generated by PBSIM3. 
#           The datasets have varying readlength, sequencing depth and error rate
# Author: Paula Uittenbogaard
# Date: 11-04-2025

if config['method'] == "ONT":
    assembly_in_dir = pbsim_dir
elif config['method'] == "HiFi":
    assembly_in_dir = ccs_dir

rule raven:
    input: 
        f"{assembly_in_dir}/{prefix}_0001.fq.gz"
    output:
        f"{raven_dir}/{prefix}.contigs.fasta"
    log:
        f"{raven_dir}/{prefix}.log"
    shell:
        """
        raven {input} > {output} 2> {log}
        """