#  ////////*                                              
#         *///////////                                    
# //////////*   ////////////                              
#           ,/////////////////                            
# /////////////////////////////    ./////                 
#            //////////////////   ////// .///             
#     *///////////////////////// .//////.     ///         
#                 //////////////.  */////,*////  .//      
#                   /////////////.     ,/////  ,///* //   
#                     /////////////       /////      ,/*, 
#                      .//////////////.  ///////          
#                         //////////////////////          
#                             ,/////,*/////////           
#                               //////////////            
#                            ///////////////              
#                           /////////////                 
#                         ,/////////*                     
#                    .////////.                           

# This SnakeMake file contains the rule to run wtdbg2
# Project: longread simulation study
# Description: perform de novo assembly on the simulated reads generated by PBSIM3. 
#           The datasets have varying readlength, sequencing depth and error rate
# Author: Paula Uittenbogaard
# Date: 25-04-2025

rule wtdbg2:
    input: 
        f"{pbsim_dir}/{prefix}_0001.fq.gz"
    output:
        f"{wtdbg2_dir}/{prefix}.ctg.lay.gz"
    log:
        f"{wtdbg2_dir}/{prefix}.log"
    params:
        prefix = f"{wtdbg2_dir}/{prefix}"
    shell:
        """
        wtdbg2 -x preset2 -g 1m -t 16 -i {input} \
        -o {params.prefix} \
        2> {log}
        """

rule wtpoa:
    input: 
        f"{wtdbg2_dir}/{prefix}.ctg.lay.gz"
    output:
        f"{wtdbg2_dir}/{prefix}.contigs.fasta"
    log:
        f"{wtdbg2_dir}/{prefix}.log"
    shell:
        """
        wtpoa-cns -t 16 -i {input} -o {output} 2>> {log}
        """