#  ////////*                                              
#         *///////////                                    
# //////////*   ////////////                              
#           ,/////////////////                            
# /////////////////////////////    ./////                 
#            //////////////////   ////// .///             
#     *///////////////////////// .//////.     ///         
#                 //////////////.  */////,*////  .//      
#                   /////////////.     ,/////  ,///* //   
#                     /////////////       /////      ,/*, 
#                      .//////////////.  ///////          
#                         //////////////////////          
#                             ,/////,*/////////           
#                               //////////////            
#                            ///////////////              
#                           /////////////                 
#                         ,/////////*                     
#                    .////////.                           

# This SnakeMake file contains the rule to run lja
# Project: longread simulation study
# Description: perform de novo assembly on the simulated reads generated by PBSIM3 followed by ccs to generate HiFi consensus reads. 
#           The datasets have varying readlength, sequencing depth and error rate
# Author: Paula Uittenbogaard
# Date: 07-05-2025

rule lja:
    input: 
        f"{ccs_dir}/{prefix}.fastq.gz"
    output:
        lja_out = f"{lja_dir}/assembly.fasta"
        #renamed_out = f"{lja_dir}/{prefix}.fasta"
    log:
        f"{lja_dir}/{prefix}.log"
    params:
        outdir = f"{lja_dir}"
    shell:
        """
        lja -o {params.outdir} --reads {input}
        """

rule move_output_lja:
    input:
        f"{lja_dir}/assembly.fasta"
    output:
        f"{lja_dir}/{prefix}.contigs.fasta"
    shell:
        """
        mv {input} {output}
        """